amino_acids = [
    ("Alanine", "Ala", 'A'),
    ("Arginine", "Arg", 'R'),
    ("Asparagine", "Asn", 'N'),
    ("Aspartate", "Asp", 'D'),
    ("Cysteine", "Cys", 'C'),
    ("Glutamine", "Gln", 'Q'),
    ("Glutamate", "Glu", 'E'),
    ("Glycine", "Gly", 'G'),
    ("Histidine", "His", 'H'),
    ("Isoleucine", "Ile", 'I'),
    ("Leucine", "Leu", 'L'),
    ("Lysine", "Lys", 'K'),
    ("Methionine", "Met", 'M'),
    ("Phenylalanine", "Phe", 'F'),
    ("Proline", "Pro", 'P'),
    ("Serine", "Ser", 'S'),
    ("Threonine", "Thr", 'T'),
    ("Tryptophan", "Trp", 'W'),
    ("Tyrosine", "Tyr", 'Y'),
    ("Valine", "Val", 'V')
]

inverse_codon = {
    ("Ala", 'A') : (("GCU", "GCC", "GCA", "GCG")),
    ("Arg", 'R') : (("CGU", "CGC", "CGA", "CGG"), ("AGA", "AGG")),
    ("Asn", 'N') : (("AAU", "AAC")),
    ("Asp", 'D') : (("GAU", "GAC")),
    ("Asn", "Asp", 'B') : (("AAU", "AAC"), ("GAU", "GAC")),
    ("Cys", 'C') : (("UGU", "UGC")),
    ("Gln", 'Q') : (("CAA", "CAG")),
    ("Glu", 'E') : (("GAA", "GAG")),
    ("Gln", "Glu", 'Z') : (("CAA", "CAG"), ("GAA", "GAG")),
    ("Gly", 'G') : (("GGU", "GGC", "GGA", "GGG")),
    ("His", 'H') : (("CAU", "CAC")),
    ("Ile", 'I') : (("AUU", "AUC", "AUA"))
    ("Leu", 'L') : (("CUU", "CUC", "CUA", "CUG"), "UUA", "UUG")),
    ("Lys", 'K') : (("AAA", "AAG")),
    ("Met", 'M') : (("AUG")),
    ("Phe", 'F') : (("UUU", "UUC")),
    ("Pro", 'P') : (("CCU", "CCC", "CCA", "CCG")),
    ("Ser", 'S') : (("UCU", "UCC", "UCA", "UCG"), ("AGU", "AGC")),
    ("Thr", 'T') : (("ACU", "ACC", "ACA", "ACG")),
    ("Trp", 'W') : (("UGG")),
    ("Tyr", 'Y') : (("UAU", "UAC")),
    ("Val", 'V') : (("GUU", "GUC", "GUA", "GUG")),
    ("START") : (("AUG", "CUG", "UUG")),
    ("STOP") : (("UAA", "UGA", "UAG"))
}

codon = {
    "UUU" : ("Phe", 'F'),
    "UUC" : ("Phe", 'F'),
    "UUA" : ("Leu", 'L'),
    "UUG" : ("Leu", 'L'), # Start codon
    "CUU" : ("Leu", 'L'),
    "CUC" : ("Leu", 'L'),
    "CUA" : ("Leu", 'L'),
    "CUG" : ("Leu", 'L'),
    "AUU" : ("Ile", 'I'),
    "AUC" : ("Ile", 'I'),
    "AUA" : ("Ile", 'I'),
    "AUG" : ("Met", 'M'), # Start codon
    "GUU" : ("Val", 'V'),
    "GUC" : ("Val", 'V'),
    "GUA" : ("Val", 'V'),
    "GUG" : ("Val", 'V'), # Start codon
    "UCU" : ("Ser", 'S'),
    "UCC" : ("Ser", 'S'),
    "UCA" : ("Ser", 'S'),
    "UCG" : ("Ser", 'S'),
    "CCU" : ("Pro", 'P'),
    "CCC" : ("Pro", 'P'),
    "CCA" : ("Pro", 'P'),
    "CCG" : ("Pro", 'P'),
    "ACU" : ("Thr", 'T'),
    "ACC" : ("Thr", 'T'),
    "ACA" : ("Thr", 'T'),
    "ACG" : ("Thr", 'T'),
    "GCU" : ("Ala", 'A'),
    "GCC" : ("Ala", 'A'),
    "GCA" : ("Ala", 'A'),
    "GCG" : ("Ala", 'A'),
    "UAU" : ("Tyr", 'Y'),
    "UAC" : ("Tyr", 'Y'),
    "UAA" : ("STOP"),
    "UAG" : ("STOP"),
    "CAU" : ("His", 'H'),
    "CAC" : ("His", 'H'),
    "CAA" : ("Gln", 'Q'),
    "CAG" : ("Gln", 'Q'),
    "AAU" : ("Asn", 'N'),
    "AAC" : ("Asn", 'N'),
    "AAA" : ("Lys", 'K'),
    "AAG" : ("Lys", 'K'),
    "GAU" : ("Asp", 'D'),
    "GAC" : ("Asp", 'D'),
    "GAA" : ("Glu", 'E'),
    "GAG" : ("Glu", 'E'),
    "UGU" : ("Cys", 'C'),
    "UGC" : ("Cys", 'C'),
    "UGA" : ("STOP"),
    "UGG" : ("Trp", 'W'),
    "CGU" : ("Arg", 'R'),
    "CGC" : ("Arg", 'R'),
    "CGA" : ("Arg", 'R'),
    "CGG" : ("Arg", 'R'),
    "AGU" : ("Ser", 'S'),
    "AGC" : ("Ser", 'S'),
    "AGA" : ("Arg", 'R'),
    "AGG" : ("Arg", 'R'),
    "GGU" : ("Gly", 'G'),
    "GGC" : ("Gly", 'G'),
    "GGG" : ("Gly", 'G'),
    "GGG" : ("Gly", 'G')
}

start_codon = {
    "UUG" : ("START"),
    "AUG" : ("START"),
    "GUG" : ("START"),
    "UAA" : ("STOP"),
    "UAG" : ("STOP"),
    "UGA" : ("STOP")
}

